
EXTRA_CFLAGS := 
# CFLAGS_file.o := 

source_files :=
source_files += $(wildcard $(PROJ_ROOT)/app/app_impl/source/*.c)
source_files += $(wildcard $(PROJ_ROOT)/app/main/source/*.c)

objects += $(subst .c,.o,$(source_files))
